version: '3'
services:
  db:
    container_name: pia-community-db
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: pia-user
      POSTGRES_PASSWORD: pia-test
    ports:
      - "5432:5432"
  web:
    container_name: pia-community-web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pia-back
    environment:
      REDIS_URL: "redis://localhost:6379/1"
      ALLOWED_CORS_ORIGINS: "*"
      RAILS_SERVE_STATIC_FILES: 'true'
    ports:
      - "3000:3000"
    depends_on:
      - db
