development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: pia_development
  pool:     5
  username: 
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: pia_test
  pool:     5
  username:
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: pia_production
  pool:     5
  username:
  password:
  template: template0
